// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvr4xVuxbmbnzI-u7bVwwMg-p5f5QvihE',
    appId: '1:259930456506:web:cc7b6d93d128cd5f4bdd83',
    messagingSenderId: '259930456506',
    projectId: 'strange-sound',
    authDomain: 'strange-sound.firebaseapp.com',
    storageBucket: 'strange-sound.appspot.com',
    measurementId: 'G-VWWMECKCYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-bBaXAIaCPbqY28KQnkCY7mXfzoeOvAI',
    appId: '1:259930456506:android:f14095d67eb8cba84bdd83',
    messagingSenderId: '259930456506',
    projectId: 'strange-sound',
    storageBucket: 'strange-sound.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVeQ9kJs2azx0TZ9ocVXjpTkOvAr0DTlY',
    appId: '1:259930456506:ios:522d6235e5b98cc24bdd83',
    messagingSenderId: '259930456506',
    projectId: 'strange-sound',
    storageBucket: 'strange-sound.appspot.com',
    iosClientId: '259930456506-av1io3c71ajdq8gheh6hbfc6l4uj8vof.apps.googleusercontent.com',
    iosBundleId: 'com.example.strangeSounds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVeQ9kJs2azx0TZ9ocVXjpTkOvAr0DTlY',
    appId: '1:259930456506:ios:522d6235e5b98cc24bdd83',
    messagingSenderId: '259930456506',
    projectId: 'strange-sound',
    storageBucket: 'strange-sound.appspot.com',
    iosClientId: '259930456506-av1io3c71ajdq8gheh6hbfc6l4uj8vof.apps.googleusercontent.com',
    iosBundleId: 'com.example.strangeSounds',
  );
}
